NPD=--no-print-directory

all: FORCE
	make $(NPD) -C ../ all

debug: FORCE
	make $(NPD) -C ../ debug

release: FORCE
	make $(NPD) -C ../ release

test: FORCE
	make $(NPD) -C ../ test

run_debug: FORCE
	make $(NPD) -C ../ run_debug

run_debug2: FORCE
	make $(NPD) -C ../ run_debug2

run_release: FORCE
	make $(NPD) -C ../ run_release

run_test:  FORCE
	make $(NPD) -C ../ run_test

run_test2: FORCE
	make $(NPD) -C ../ run_test2

clean: FORCE
	make $(NPD) -C ../ clean

FORCE:





